[env:esp32-s3-n16r8]
platform = espressif32 @ 6.13.0
board = esp32-s3-devkitc-1
framework = arduino, espidf

; --- SETTING HARDWARE N16R8 ---
board_build.arduino.memory_type = dio_opi
board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_build.psram_type = opi
board_upload.flash_size = 16MB


build_flags = 
    -DCONFIG_ESP_WIFI_MGMT_S3_RETRY=y
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_SPIRAM_SUPPORT=1
    -DCONFIG_SPIRAM_MODE_OPI=1
    -DCONFIG_ESP_WIFI_SOFTAP_SUPPORT=y
    -DCONFIG_ESP_WIFI_PROMISCUOUS_SUPPORT=y
    -DCONFIG_ESP_WIFI_80211_TX=y
    -DCONFIG_ESP_WIFI_80211_TX_BYPASS=y
    DCONFIG_SOC_WIFI_CSI_SUPPORT=y
    -DCONFIG_SOC_WIFI_MESH_SUPPORT=y
    -O3

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.15.0
    Wire
    SPI
